name: Flutter CI/CD (Android Only)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Flutter with the correct version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # Use the latest stable version

      # Verify Flutter version and Dart SDK version
      - name: Verify Flutter and Dart versions
        run: |
          flutter --version
          dart --version  # Verify that the Dart SDK is the correct version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # # Run tests (no --release flag for tests)
      # - name: Run tests
      #   run: flutter test

      # Build the Android APK
      - name: Build Android APK
        run: flutter build apk --release  # Build the release APK

      # Upload APK (Android)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
